import { ReduxProvider } from '@/redux/store/ReduxProvider'
import "../../public/globals.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className='dark'
    >
      <body className={`${inter.className} 
      bg-grey-100 text-black dark:bg-dark-200 dark:text-white
      treansition-colors duration-300 ease-in
      `}>

        <main>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </main>
      </body>
    </html>
  )
}
