# Generated by Django 4.2.7 on 2023-12-07 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("post", "0001_initial"),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortcomment",
            name="short_video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="short_comments",
                to="post.shortvideo",
            ),
        ),
    ]
