# Generated by Django 4.2.7 on 2023-11-29 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0007_remove_shortvideo_dislikes_remove_shortvideo_likes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment", "0005_comment_content_type_comment_object_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "short_video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.shortvideo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Short_Comment",
                "verbose_name_plural": "Short_Comments",
                "ordering": ["-pk"],
            },
        ),
        migrations.RemoveField(
            model_name="comment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="object_id",
        ),
        migrations.DeleteModel(
            name="Short_Comment",
        ),
    ]
