# Generated by Django 4.2.7 on 2023-12-01 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0007_remove_shortvideo_dislikes_remove_shortvideo_likes_and_more"),
        ("comment", "0006_shortcomment_remove_comment_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="post.video",
            ),
        ),
        migrations.AlterField(
            model_name="shortcomment",
            name="short_video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="short_comments",
                to="post.shortvideo",
            ),
        ),
    ]
