version: '3.11'
services:
  backend:
    container_name: django-backend
    build: .
    volumes: 
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user 
      - POSTGRES_DB=django
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: