# Generated by Django 4.2.7 on 2023-12-07 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("post", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="video_dislikes_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="video_dislikes",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="video_likes_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="video_likes",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(blank=True, to="post.tag"),
        ),
        migrations.AddField(
            model_name="video",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="uservideointeraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="uservideointeraction",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="post.video"
            ),
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="post.category",
            ),
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="short_video_dislikes_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="short_video_dislikes",
            ),
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="short_video_likes_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="short_video_likes",
            ),
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="post.tag"),
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uservideointeraction",
            unique_together={("user", "video")},
        ),
    ]
