# Generated by Django 4.2.7 on 2023-11-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shortvideo",
            options={
                "ordering": ("-upload_date",),
                "verbose_name": "Short Video",
                "verbose_name_plural": "Short Videos",
            },
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shortvideo",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
