# Generated by Django 4.2.7 on 2023-11-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_shortvideo_options_shortvideo_dislikes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortvideo",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="post.tag"),
        ),
        migrations.AlterField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="post.tag"),
        ),
    ]
