# Generated by Django 4.2.7 on 2023-11-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_shortvideo_tags_alter_video_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortvideo",
            name="tags",
            field=models.ManyToManyField(to="post.tag"),
        ),
        migrations.AlterField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(to="post.tag"),
        ),
    ]
