# Generated by Django 4.2.7 on 2023-11-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_alter_shortvideo_tags_alter_video_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortvideo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="post.tag"),
        ),
        migrations.AlterField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(blank=True, to="post.tag"),
        ),
    ]
