# Generated by Django 4.2.7 on 2023-11-28 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0006_alter_shortvideo_tags_alter_video_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shortvideo",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="shortvideo",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="video",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="video",
            name="likes",
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="short_video_dislikes_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="short_video_dislikes",
            ),
        ),
        migrations.AddField(
            model_name="shortvideo",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="short_video_likes_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="short_video_likes",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="video_dislikes_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="video_dislikes",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="video_likes_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="video_likes",
            ),
        ),
    ]
