# Generated by Django 4.2.7 on 2023-11-28 01:29

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="static/images/default_profile_image.png",
                upload_to=apps.user.models.user_image,
            ),
        ),
    ]
