# Generated by Django 4.2.7 on 2023-12-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
