# Generated by Django 4.2.7 on 2023-12-04 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="picture",
            new_name="picture_url",
        ),
    ]
